# Generated by Django 4.1.7 on 2026-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_shippingprice_alter_order_taxprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
